#define ID_STATUSBAR                  10
#define ID_MAINACCELERATORS           11
#define ID_TOOLBAR                    12

#define ID_MAINICON                   100
#define ID_DOCUMENTICON               101
#define ID_EXPLORERICONS              102
#define ID_TOOLBARICONS               103

#define ID_FILE                       200
#define ID_FILE_NEW                   230
#define ID_FILE_NEW_PROJECT           231
#define ID_FILE_NEW_EMPTY             232
#define ID_FILE_NEW_TEMP              233
#define ID_FILE_OPEN                  201
#define ID_FILE_SAVE                  202
#define ID_FILE_SAVEAS                203
#define ID_FILE_SAVEALL               204
#define ID_FILE_SAVEPROJ              205
#define ID_FILE_SAVETEMPLATE          206
#define ID_FILE_CLOSEDOC              207
#define ID_FILE_CLOSEALL              208
#define ID_FILE_CLOSEOTHERS           209
#define ID_FILE_PRINT                 210
#define ID_FILE_ADDPROJECTFILE        211
#define ID_FILE_REMOVEPROJECTFILE     212
#define ID_FILE_REMOVEFROMPROJECT     213
#define ID_FILE_ADDPROJECTFOLDER      214
#define ID_FILE_OPENFILE              215
#define ID_FILE_CLOSEFILE             216
#define ID_FILE_ADDTOPROJECT          217
#define ID_FILE_EXIT                  218

#define ID_EDIT                       300
#define ID_EDIT_UNDO                  301
#define ID_EDIT_REDO 	                302
#define ID_EDIT_CUT	                  303
#define ID_EDIT_COPY                  304
#define ID_EDIT_PASTE                 305
#define ID_EDIT_SELECTALL             306
#define ID_EDIT_FIND                  307
#define ID_EDIT_FINDNEXT              308
#define ID_EDIT_INDENT                309
#define ID_EDIT_UNINDENT              310
#define ID_EDIT_FORMAT                311
#define ID_EDIT_TOGGLEBOOKMARK        312
#define ID_EDIT_TOGGLEBOOKMARK_1      313
#define ID_EDIT_TOGGLEBOOKMARK_2      314
#define ID_EDIT_TOGGLEBOOKMARK_3      315
#define ID_EDIT_TOGGLEBOOKMARK_4      316
#define ID_EDIT_TOGGLEBOOKMARK_5      317
#define ID_EDIT_TOGGLEBOOKMARK_6      318
#define ID_EDIT_TOGGLEBOOKMARK_7      319
#define ID_EDIT_TOGGLEBOOKMARK_8      320
#define ID_EDIT_TOGGLEBOOKMARK_9      321
#define ID_EDIT_TOGGLEBOOKMARK_0      322
#define ID_EDIT_GOTOBOOKMARK          323
#define ID_EDIT_GOTOBOOKMARK_1        324
#define ID_EDIT_GOTOBOOKMARK_2        325
#define ID_EDIT_GOTOBOOKMARK_3        326
#define ID_EDIT_GOTOBOOKMARK_4        327
#define ID_EDIT_GOTOBOOKMARK_5        328
#define ID_EDIT_GOTOBOOKMARK_6        329
#define ID_EDIT_GOTOBOOKMARK_7        330
#define ID_EDIT_GOTOBOOKMARK_8        331
#define ID_EDIT_GOTOBOOKMARK_9        332
#define ID_EDIT_GOTOBOOKMARK_0        333
#define ID_EDIT_GOTOLINE              334
#define ID_EDIT_RENAMEDOCUMENT        335
#define ID_EDIT_RENAMEPROJECTFILE     336
#define ID_EDIT_DOCPROPERTIES         337
#define ID_EDIT_FILEPROPERTIES        338
#define ID_EDIT_PREFERENCES           339
#define ID_EDIT_OVERWRITEMODE         340
#define ID_EDIT_PROJECTEXPLORER       341

#define ID_TOOL                       500
#define ID_TOOL_INSERT                501
#define ID_TOOL_INSERTCHAR            502
#define ID_TOOL_INSERTSINGLETAG       503
#define ID_TOOL_INSERTPAIREDTAG       504
#define ID_TOOL_INSERTCOLOR           505
#define ID_TOOL_INSERTDATETIME        506
#define ID_TOOL_CHARTOHTML            507
#define ID_TOOL_HTMLTOCHAR            508
#define ID_TOOL_AUTOCONVERT           509
#define ID_TOOL_LOWERCASEHTML         510
#define ID_TOOL_UPPERCASEHTML         511
#define ID_TOOL_BROWSEDOC             512
#define ID_TOOL_BROWSEFILE            513
#define ID_TOOL_VALIDATEDOC           514
#define ID_TOOL_VALIDATEFILE          515

#define ID_HELP                       600
#define ID_HELP_UPDATE                601
#define ID_HELP_ABOUT                 602


#define ID_ABOUTDIALOG                1000
#define ID_OKBTN                      1001
#define ID_CANCELBTN                  1002
#define ID_ABOUTLINK                  1003

#define ID_INPUTDIALOG                1010
#define ID_INPUTLBL                   1011
#define ID_INPUTEDT                   1012

#define ID_FINDDIALOG                 1101
#define ID_FINDLBL                    1102
#define ID_FINDCMB                    1103
#define ID_REPLACELBL                 1104
#define ID_REPLACECMB                 1105
#define ID_OPTIONSGRP                 1106
#define ID_MATCHCASECHK               1107
#define ID_FROMCURSORCHK              1108
#define ID_WHOLEWORDSCHK              1109
#define ID_DIRECTIONGRP               1110
#define ID_PREVIOUSRBN                1111
#define ID_NEXTRBN                    1112
#define ID_REPLACEFINDBTN             1113
#define ID_REPLACEBTN                 1114
#define ID_REPLACEALLBTN              1115

#define ID_PROPERTIESDIALOG           1200
#define ID_NAMELBL                    1201
#define ID_NAMEEDT                    1202
#define ID_LOCATIONLBL                1203
#define ID_LOCATIONEDT                1204
#define ID_TYPELBL                    1205
#define ID_TYPEEDT                    1206
#define ID_HORZLINE1                  1207
#define ID_SIZELBL                    1208
#define ID_SIZEEDT                    1209
#define ID_HORZLINE2                  1210
#define ID_DATECREATEDLBL             1211
#define ID_DATECREATEDEDT             1212
#define ID_DATEMODIFIEDLBL            1213
#define ID_DATEMODIFIEDEDT            1214
#define ID_SYSPROPERTIESBTN           1215

#define ID_GOTODIALOG                 1300
#define ID_LINELBL                    1301
#define ID_LINEEDT                    1302
#define ID_COLLUMNLBL                 1303
#define ID_COLLUMNEDT                 1304

#define ID_DATETIMEDIALOG             1400
#define ID_DATEFORMATLBL              1401
#define ID_DATEFORMATCMB              1402
#define ID_TIMEFORMATLBL              1403
#define ID_TIMEFORMATCMB              1404
#define ID_DATETIMEPREVIEWLBL         1405

#define ID_PREFERENCESDIALOG1         2100
#define ID_MULTIPLEINSTANCESCHK       2101
#define ID_AUTOUPDATECHK              2102
#define ID_OVERWRITEEMPTYDOCSCHK      2103
#define ID_OPENUNSUPPORTEDDOCSCHK     2104
#define ID_HIDEEXPLORERCHK            2105
#define ID_OPENEXPFILEONSELCHK        2106
#define ID_RENAMEEXPONSELCHK          2107
#define ID_AUTOHIDEEXPLORERCHK        2108
#define ID_AUTOHIDEDELAYLBL           2109
#define ID_AUTOHIDEDELAYEDT           2110
#define ID_DEFAULTBROWSERCHK          2111
#define ID_INTERNETBROWSERLBL         2112
#define ID_INTERNETBROWSEREDT         2113
#define ID_INTERNETBROWSERBTN         2114

#define ID_PREFERENCESDIALOG2         2200
#define ID_OVERWRITESELECTIONCHK      2201
#define ID_OVERWRITETEXTCHK           2202
#define ID_AUTOINDENTCHK              2203
#define ID_GROUPUNDOCHK               2204
#define ID_DBLCLKSELLINECHK           2205
#define ID_SPACESEPARATEDWORDSCHK     2206
#define ID_TABINDENTSLINESCHK         2207
#define ID_INDENTSIZELBL              2208
#define ID_INDENTSIZEEDT              2209
#define ID_DEFAULTSCROLLCOUNTCHK      2210
#define ID_SCROLLLINECOUNTLBL         2211
#define ID_SCROLLLINECOUNTEDT         2212

#define ID_PREFERENCESDIALOG3         2300
#define ID_SHOWGUTTERCHK              2301
#define ID_SHOWMARGINCHK              2302
#define ID_SHOWLINENUMBERSCHK         2303
#define ID_AUTOSIZEGUTTERCHK          2304
#define ID_GUTTERSIZELBL              2305
#define ID_GUTTERSIZEEDT              2306
#define ID_MARGINSIZELBL              2307
#define ID_MARGINSIZEEDT              2308
#define ID_EDITORFONTLBL              2309
#define ID_EDITORFONTCMB              2310
#define ID_EDITORFONTSIZELBL          2311
#define ID_EDITORFONTSIZECMB          2312
#define ID_EDITORFONTPREVIEWLBL       2313
#define ID_GUTTERFONTLBL              2314
#define ID_GUTTERFONTCMB              2315
#define ID_GUTTERFONTSIZELBL          2316
#define ID_GUTTERFONTSIZECMB          2317
#define ID_GUTTERFONTPREVIEWLBL       2318

#define ID_PREFERENCESDIALOG4         2400

#define ID_PREFERENCESDIALOG5         2500
#define ID_TEXTFILESCHK               2501
#define ID_HTMLFILESCHK               2502
#define ID_STYLESHEETFILESCHK         2503
#define ID_JAVASCRIPTFILESCHK         2504
#define ID_PHPFILESCHK                2505
#define ID_ALLFILESBTN                2506
#define ID_NOFILESBTN                 2507

#define ID_TOOL_INSERTCHAR_ITEM       9000
#define ID_TOOL_INSERTSINGLETAG_ITEM  9200
#define ID_TOOL_INSERTPAIREDTAG_ITEM  9300
